# This Ansible role is responsible for configuring a newly installed Proxmox VE.
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster
---
- name: add pve repository key
  apt_key:
    url: "{{ pve_repo_keyurl }}"
    keyring: "{{ pve_repo_keyring }}"
    state: present

- name: add pve-no-subscription repo
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    state: present
    filename: 'pve-install-repo'

- name: update system
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove subscription warning in UI
  patch:
    src: "pve_non_enterprise_ui.patch"
    basedir: /
    strip: 1
    backup: yes