# Configure Proxmox VE
---
- hosts: happy_garden
  gather_facts: true
  become: yes
  become_method: sudo  # need to pass -kK for password
  roles:
    - {
        role: ../roles/proxmox,
        pve_group: happy_garden,
        pve_run_system_upgrades: true,
        pve_reboot_on_kernel_update: true
    }
